package GUI;



import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Menumodulo extends javax.swing.JFrame {
    //ArrayList<Persona> personasLectura = ma.LeerDatosDeArchivo();

    public Menumodulo() throws IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        titulomain = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        Almuerzos = new javax.swing.JButton();
        Planillas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainpanel.setBackground(new java.awt.Color(100, 100, 225));

        titulomain.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulomain.setText("El Colegio");

        Registrar.setBackground(new java.awt.Color(85, 200, 80));
        Registrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Registrar.setForeground(new java.awt.Color(0, 0, 0));
        Registrar.setText("Registro");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setForeground(new java.awt.Color(0, 0, 0));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        Almuerzos.setBackground(new java.awt.Color(85, 200, 80));
        Almuerzos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Almuerzos.setForeground(new java.awt.Color(0, 0, 0));
        Almuerzos.setText("Almuerzos");
        Almuerzos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmuerzosActionPerformed(evt);
            }
        });

        Planillas.setBackground(new java.awt.Color(85, 200, 80));
        Planillas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Planillas.setForeground(new java.awt.Color(0, 0, 0));
        Planillas.setText("Planillas");
        Planillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanillasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(Registrar)
                .addGap(99, 99, 99)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titulomain)
                    .addComponent(Almuerzos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(Planillas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(titulomain)
                .addGap(45, 45, 45)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Almuerzos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Planillas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(exit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        registro registro = new registro();
        registro.setVisible(true);
        registro.setLocationRelativeTo(this);
     
    }//GEN-LAST:event_RegistrarActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void AlmuerzosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmuerzosActionPerformed
          
      
    }//GEN-LAST:event_AlmuerzosActionPerformed

    private void PlanillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanillasActionPerformed
       
    }//GEN-LAST:event_PlanillasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Almuerzos;
    private javax.swing.JButton Planillas;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton exit;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JLabel titulomain;
    // End of variables declaration//GEN-END:variables
}
